# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
        ('music', '0003_auto_20160831_2043'),
    ]

    operations = [
    ]
